### PR TITLE
Add random_password function to generate alphanumeric passwords

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by raphink** [comment]
How do you use that idempotently?

**Comment by domcleal** [comment]
@raphink with [cache_data](https://github.com/puppet-community/puppet-extlib#cache_data)

**Comment by raphink** [comment]
Ah, good to know @domcleal!

**Comment by igalic** [comment]
@ehelms you should perhaps document how to use this idempotently :)

**Comment by nibalizer** [comment]
I too would like more docs but the function was well enough documented in this PR. Another PR to show the composition would be appreciated.

**Pull request merged**
