### PR TITLE
Add "echo" function for debugging

### PR DESCRIPTION
**Pull request by dmitryilyin**
* Move tests to spec/puppet/parser/functions

### CODE REVIEW

**Comment by igalic** [comment]
i'm unclear how this is in any way different from adding [debug("${var}")](https://docs.puppetlabs.com/references/latest/function.html#debug) — most of the time you'll know what $var is (string, array, hash, etc…), and most of the time debug will already convert it correctly to a string.

**Comment by dmitryilyin** [comment]
Standard debug is not very good at inspecting values, it does'n show the exact type of a variable and doesn't render arrays as arrays, working with boolean and undef values is not good to. Its hard to tell some sorner case values one from another. Also sometimes i need to catch numeric and symbol values or even complex objects that get into the catalog where they don't belong.
My function also has "comment" feature to mark location from where values come from.

**Comment by dmitryilyin** [comment]
"echo" is also named friendly to Shell and PHP developers)

**Comment by igalic** [comment]
noted.

i'm a bit confused about the rename of resources_deep_merge_spec.rb — what happened there?

**Comment by dmitryilyin** [comment]
I have moved specs to spec/functions yo make use of rspec-puppet helpers for functions. I have also refactored all specs to the correct notation and added readme about echo.

**Comment by igalic** [comment]
excellent. thank you. @dmitryilyin!

**Pull request merged**
